/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.food.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import sun.text.SupplementaryCharacterData;

import com.food.delegate.GeneralDelegate;
import com.food.delegate.FoodDelegate;
import com.food.exception.ConnectionException;
import com.food.formbean.GeneralFormBean;
import com.food.formbean.FoodFormBean;
import com.food.pojo.TipsSuggestions;
import com.food.pojo.Restaurant;
import com.food.util.UtilConstants;

/** 
 * MyEclipse Struts
 * Creation date: 09-26-2012
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/Status.jsp"
 */
public class AddRestaurantDetailsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		FoodFormBean foodFormBean = (FoodFormBean) form;
		Restaurant restaurant = new Restaurant(foodFormBean);
		boolean flag = false;
		System.out.println("haii");
		try {
			flag = new FoodDelegate().addRestaurentDetails(restaurant);
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._FOOD_SUPPLY_SUCCESS);
			return mapping.findForward(UtilConstants._SUCCESS);
		} catch (ConnectionException e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward(UtilConstants._SUCCESS);
		} catch (Exception e) {
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._TIPS_FAILURE);
			return mapping.findForward(UtilConstants._SUCCESS);
		}

	}
}