/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.food.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.food.delegate.GeneralDelegate;
import com.food.delegate.FoodDelegate;
import com.food.exception.ConnectionException;
import com.food.formbean.FoodFormBean;
import com.food.pojo.Education;
import com.food.pojo.FoodInfoPojo;
import com.food.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 09-28-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/FoodInfoAction" name="FoodFormBean" scope="request"
 *                validate="true"
 * @struts.action-forward name="succes" path="/Status.jsp"
 */
public class FoodInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		FoodFormBean foodFormBean = (FoodFormBean) form;// TODO
		// Auto-generated
		// method stub
		FoodInfoPojo foodInfoPojo = new FoodInfoPojo(foodFormBean);
		System.out.println("FOOD :------"+foodInfoPojo.getFood());
		boolean flag = false;
		try {
			flag = new FoodDelegate().addFoodInforamtion(foodInfoPojo);
			request.setAttribute(UtilConstants._STATUS, foodInfoPojo
					.getFood()
					+ " Information added SuddessFully........");
			return mapping.findForward(UtilConstants._SUCCESS);
		} catch (ConnectionException e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward(UtilConstants._SUCCESS);
		} catch (Exception e) {
			request.setAttribute(UtilConstants._STATUS, foodInfoPojo
					.getFood()
					+ " Information added Operation Fail.");
			return mapping.findForward(UtilConstants._SUCCESS);
		}

	}
}