/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.food.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.food.delegate.RegionalInfoDelegate;
import com.food.delegate.FoodDelegate;
import com.food.exception.ConnectionException;
import com.food.formbean.FoodFormBean;
import com.food.pojo.District;
import com.food.pojo.Restaurant;
import com.food.util.UtilConstants;

/** 
 * MyEclipse Struts
 * Creation date: 09-26-2012
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/Status.jsp"
 */
public class UpdateRestaurantDetailsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		FoodFormBean foodFormBean=(FoodFormBean)form;
		Restaurant restaurant = new Restaurant(foodFormBean);
		System.out.println(request.getParameter("restarantid"));
		System.out.println(Integer.parseInt(request.getParameter("restarantid")));
		System.out.println(Integer.parseInt(request.getParameter("restarantid").toString()));
		restaurant.setRestarantid(Integer.parseInt(request.getParameter("restarantid").toString()));
		boolean flag = false;
		try {
			flag = new FoodDelegate().updateRestaurant(restaurant);
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._UPDATE_FOOD_SUPPLY_SUCCESS);
			return mapping.findForward("success");
		} catch (ConnectionException e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward("success");
		} catch (Exception e) {
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants.__ADD_STATE_FAIL);
			return mapping.findForward("success");
		}
	}
}