/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.food.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;

import com.food.delegate.RegionalInfoDelegate;
import com.food.delegate.SecurityUserDelegate;
import com.food.exception.ConnectionException;
import com.food.formbean.ProfileFormBean;
import com.food.formbean.RegionalFormBean;
import com.food.pojo.Addresses;
import com.food.pojo.City;
import com.food.pojo.LoginDetails;
import com.food.pojo.UserDetails;
import com.food.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 09-20-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/UserRegisterAction" name="profileFormBean"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/UserRegistrationForm.jsp"
 */
public class UserRegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		boolean flag = false;
		RegionalFormBean regionalFormBean = (RegionalFormBean) form;// TODO
		ProfileFormBean profileFormBean = (ProfileFormBean) request
				.getSession().getAttribute("profileFormBean");
		UserDetails userDetails = new UserDetails(profileFormBean);
		userDetails.setAddresses(new Addresses(regionalFormBean));
		userDetails.setLoginDetails(new LoginDetails(profileFormBean));
		
		try {
			flag = new SecurityUserDelegate().userRegistration(userDetails);
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._REGISTER_SUCCESS);
			request.getSession().setAttribute("profileFormBean", null);
			return mapping.findForward(UtilConstants._SUCCESS);
		} catch (ConnectionException e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward(UtilConstants._SUCCESS);
		} catch (Exception e) {
			System.out.println(e);
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._REGISTER_FAIL);
			return mapping.findForward(UtilConstants._SUCCESS);
		}

	}
}